### ISSUE TITLE
First Meeting

### ISSUE THREAD

**Issue by ozzieba** [cev2107/team-dirt-off-your-shoulder#2]
Hi,

Just wanted to figure out if you're around to meet.  I'm at the workshop, far right side of the room, jeans and white button-down, are you here? Want to meet now/later today? 

Oz

**Comment by jzf2101** [comment]
I'm out of town this week so I'll have to be in communication with you all
online.

On Feb 8, 2015, at 13:26, ozzieba <notifications@github.com> wrote:

Hi,

Just wanted to figure out if you're around to meet. I'm at the workshop,
far right side of the room, jeans and white button-down, are you here? Want
to meet now/later today?

Oz

—
Reply to this email directly or view it on GitHub
<https://github.com/cev2107/team-dirt-off-your-shoulder/issues/2>.

**Comment by cev2107** [comment]
Oz. My apologies, but I am away from campus.  I will be on campus tomorrow.  Are you available after 4pm?  Also, if you have any ideas, please do not hesitate to post them here.

**Comment by ericdonahue** [comment]
i had to add an extra class last week so i'm probably dropping javascript tomorrow. good luck though!

**Comment by cev2107** [comment]
Hi @levbrie @ozzieba @jzf2101 

I had to drop the class.  I am sorry that I won't be able to help out with this project.  Good luck.
